---
title: "Breast Cancer Screening in Southern Arizona"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
# packages 
library(flexdashboard)
library(tidyverse)
library(ggthemes)
library(RColorBrewer)
library(plotly)
library(leaflet)
library(tigris)
library(sf)
library(knitr)

# options
options(tigris_use_cache = TRUE)

# read data
# breast cancer screening mammogram
breast_plot <- read_rds("../../data/tidy/uazcc_brfss_mammogram_plot.rds")
breast_table <- read_rds("../../data/tidy/uazcc_brfss_mammogram_table.rds")
breast_map <- read_rds("../../data/tidy/uazcc_brfss_mammogram_map.rds")
```

Column {data-width=61.8%}
-----------------------------------------------------------------------

### Chart

```{r}
ggplotly(breast_plot) %>%
  layout(legend = list(orientation = 'h'))
```

Column {data-width=38.2%}
-----------------------------------------------------------------------

### Table

```{r}
breast_table %>%
  kable(
    col.names = c("Year", "UAZCC Catchment", "Pima County", "Pinal County", "Santa Cruz County*", "Yuma County"),
    caption = "*Santa Cruz County includes Santa Cruz, Cochise, Graham, and Greenlee counties"
  )
```

### Map

```{r}
breast_map
```

